### ISSUE TITLE
useSuspenseQuery erroring out with get SuspenceCache

### ISSUE THREAD

**Issue by clyncha** [apollographql/apollo-client-nextjs#162] opened 2024-01-05 20:42 UTC
Code in the getSuspenceCache is attempting to access defaultOptions.react but defaultOptions is undefined.

<img width="907" alt="Screenshot 2024-01-05 at 3 41 18 PM" src="https://github.com/apollographql/apollo-client-nextjs/assets/89420677/c4eb71bd-4ec0-43d4-84f6-df2ecfe141eb">

https://github.com/apollographql/apollo-client-nextjs/assets/89420677/da9a85c9-53cb-4755-9736-82c728358acb

I am seeing a similar issue when I swap out useSuspenseQuery for useQuery. It seems to be having an issue reading watchQuery

<img width="907" alt="Screenshot 2024-01-05 at 3 57 31 PM" src="https://github.com/apollographql/apollo-client-nextjs/assets/89420677/3843197a-d429-4ac4-bf93-da7dc39a56c8">

**Comment by jerelmiller** [comment] 2024-01-05 21:06
Hey @clyncha 👋 

Sorry to hear you're experiencing this! Would you be able to provide both the `@apollo/client` and `@apollo/experimental-nextjs-app-support` versions you're using?

**Comment by jerelmiller** [comment] 2024-01-05 21:08
@clyncha ah wait, I noticed in your video that your `client` is a `Promise<NextSSRApolloClient>`, which is likely the cause. This should be `NextSSRApolloClient` itself. How are you setting up your client in your code?

**Comment by clyncha** [comment] 2024-01-05 21:09
Here is how I am setting up my client

<img width="596" alt="Screenshot 2024-01-05 at 4 09 10 PM" src="https://github.com/apollographql/apollo-client-nextjs/assets/89420677/b2214a64-817a-4e91-9249-905d3b40b88e">

Thank you for responding so promptly :)

**Comment by clyncha** [comment] 2024-01-05 21:10
Here is where I am using it instead of a client component

<img width="781" alt="Screenshot 2024-01-05 at 4 09 59 PM" src="https://github.com/apollographql/apollo-client-nextjs/assets/89420677/7c8a5515-f2bc-4c26-8685-69bf10a4f034">

**Comment by jerelmiller** [comment] 2024-01-05 21:11
@clyncha can you remove that `async` keyword on your `makeClient` function? That should make the error go away. Doesn't look like you need it anyways 🙂

**Comment by clyncha** [comment] 2024-01-05 21:12
> @clyncha can you remove that `async` keyword on your `makeClient` function? That should make the error go away. Doesn't look like you need it anyways 🙂

Oh wow I feel silly now.. that worked! Thank you

**Comment by jerelmiller** [comment] 2024-01-05 21:13
You're welcome! Sometimes it helps to have an extra pair of eyes 😆. Glad to hear it worked! I'll go ahead and close this issue. Feel free to reach out if you need additional help!

**Closed by jerelmiller** 2024-01-05 21:13 UTC
