### ISSUE TITLE
DOMException [AbortError]: This operation was aborted

### ISSUE THREAD

**Issue by jasperzs** [apollographql/apollo-client-nextjs#24] opened 2023-05-13 15:38 UTC
Hi,

Thanks for putting up this awesome library! I recently started to use Apollo client to hit our graphQL api using Next.js app router. Currently, after a (SSR/SSG with `export const revalidate = xxx`) page is first loaded, then subsequently refreshing it in browser gives `DOMException [AbortError]: This operation was aborted`. From an old post while googling, I was able to make this error disappear by configuring an abortController in the httpLink, but my gut feeling tells me this probably is not the right way to address this problem. 

Could you please shed some light on how to solve this the right way? Thank you!
<img width="573" alt="image" src="https://github.com/apollographql/apollo-client-nextjs/assets/15724519/551c4c0b-24fa-4194-bd9d-4977f3eeca7e">

My apollo client configuration is this:
<img width="1804" alt="image" src="https://github.com/apollographql/apollo-client-nextjs/assets/15724519/b6254858-dd8f-4fa5-aa65-04c8d4bffe4d">

**Comment by phryneas** [comment] 2023-05-15 09:20
Could you create a minimal reproduction for this issue? I'd need to see that myself to look into that.

**Comment by jasperzs** [comment] 2023-05-29 18:19
@phryneas I found out it's this line that caused the above DOM Exception AbortError. Any idea why this line is needed?
https://github.com/apollographql/apollo-client/blob/249076fd908c79350077369961ea8e78fb06d862/src/link/http/createHttpLink.ts#L201
And in the polls-demo example, you can reproduce this issue by removing `export const dynamic` and replace it with `export const revalidate=5`.

**Comment by phryneas** [comment] 2023-05-30 09:44
I've done some digging here.

Essentially: this is the doing of Next.js, and there is probably nothing we can do about it.

You can find the related code here: 
https://github.com/vercel/next.js/blob/05f6de10869021dbb6124e174778e2108c9b4e8e/packages/next/src/server/lib/patch-fetch.ts#L231-L233

Here, Next.js calls `fetch` with the `AbortSignal` we pass in, and then it doesn't re-throw errors, but just `console.log`s and swallows then.

Now, we make every request with an `AbortSignal` and as a general cleanup, we cancel that signal at the end. Any errors that would be thrown by that are caught by us, and discarded. We can't catch & discard this `AbortError`, because Next.js handles it on their own. And honestly, in a completely irresponsible fashion. This could be any kind of error, and it will never surface.

Your workaround essentially means that you take control over the `fetch` request lifetime - we cannot stop outgoing requests anymore, and that is your job now.

Honestly, at this point I don't really know what we can do here :/ 
I'll have to discuss this internally.

Maybe you can also open an issue over at the Next repo?

**Comment by t-zander** [comment] 2023-06-16 12:40
For me it looks like this `revalidate` option is not taken into account at all.
This doesn't work
```
const { data } = await getClient().query({
      query,
      context: {
        fetchOptions: {
          next: { revalidate: 5 },
        },
      },
    });
```
and 
```
export const revalidate = 5;
```
doesn't work too.

I am taking this directly from this resource
https://www.apollographql.com/blog/apollo-client/next-js/how-to-use-apollo-client-with-next-js-13/#revalidating-graphql-requests

If I do this:
```
const { data } = await fetch(
    "https://main--time-pav6zq.apollographos.net/graphql",
    {
      method: "POST",
      body: JSON.stringify({
        query: '{ now(id: "1") }',
      }),
      headers: {
        "Content-Type": "application/json",
      },
      next: { revalidate: 10 },
    }
  ).then((res) => res.json());
```

it works perfectly fine

**Comment by phryneas** [comment] 2023-06-16 13:39
It's very possible that the fact that we cancel our AbortController after the request, and they just blindly reuse that AbortController means that their revalidation request never happens.

**Comment by phryneas** [comment] 2024-02-19 10:12
I believe this has been fixed quite a while ago in HttpLink, so I'm closing this here.

**Closed by phryneas** 2024-02-19 10:12 UTC
Labels: nextjs-bug
