### ISSUE TITLE
using SSR strategy - updating from 0.3.5 to 0.4.1 breaks SSR

### ISSUE THREAD

**Issue by ODreelist** [apollographql/apollo-client-nextjs#71] opened 2023-07-25 17:40 UTC
We went from: 

    "@apollo/client": "3.8.0-beta.6",
    "@apollo/experimental-nextjs-app-support": "^0.3.5",

to: 

"@apollo/client": "3.8.0-rc.1",
    "@apollo/experimental-nextjs-app-support": "^0.4.1",
    
I removed the `makeSuspenseCache={makeSuspenseCache}` as instructed in the Release notes, however the behavior has completely degraded. In our stripped down example, before the update, if you reload the browser, you could see the data was fetched on the server, and no subsequent client side requests were made immediately after. That is my understanding of this working as intended, and that was great.

Now, after upgrading the packages, it renders cached data from the server and then performs a client side graphql query immediately upon loading (causing next to throw rehydration mismatch errors). I hope it's something I'm missing but I have reverted back to the old libraries and everything works. Hoping you all can shed some light on this situation.

Will provide more details if necessary. It's a bog standard test setup with a list component and a simple add form/button for the create post mutation. Again the only issue is with SSR on page load/hydration and all I had to do to introduce this bad behavior is update those packages (reverting works fine).

Thanks in advance.

**Comment by phryneas** [comment] 2023-07-26 08:36
Hi there,
I'm sorry that this happens! The patch in 0.4.1 is designed to restart the query in the browser in the case that the streaming connection from the server closed before data could be fully transported over - otherwise, the browser would hang in "loading" forever. 
There seems to be something triggering that too soon for you, though. I would be *very* happy if you could get us a reproduction for that.

Maybe you could even add a failing integration test? That means you already have something to start on when building a reproduction. 
We have the integration tests here: https://github.com/apollographql/apollo-client-nextjs/blob/main/integration-test/src/app/cc/dynamic/dynamic.test.ts

[This is a test that makes sure that any requests happening client-side would fail the test](https://github.com/apollographql/apollo-client-nextjs/blob/fccfb55f2faf46d2ca05202c5535d7ae8c58defe/integration-test/src/app/cc/dynamic/dynamic.test.ts#L6-L13) (by destructuring `blockRequest` there).

**Comment by ODreelist** [comment] 2023-08-13 22:58
Unfortunately we had to use the old fashioned useQuery until we get the useSuspenseQuery issues sorted out, I wonder if it's possible that the reason it was happening is because the server side query doesn't pass the cookies so it saw a "mismatch" when the client took over (related to my new issue) but we'll keep on pushing forward!

**Comment by plausible-phry** [comment] 2023-08-15 01:40
Without a reproduction there is unfortunately not much we can do to help you sort this out. Could you please take the time to create a small reproduction?

(Gonna take a look at your new issue now)

**Comment by phryneas** [comment] 2024-02-19 10:15
I believe this was fixed in 0.4.3, so I'll close this issue.

**Closed by phryneas** 2024-02-19 10:15 UTC
